# Generated by Django 3.1.1 on 2020-09-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20)),
                ('rname', models.CharField(max_length=20)),
                ('remail', models.EmailField(max_length=254)),
                ('rpassword', models.CharField(max_length=20)),
                ('rcontact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'resident',
            },
        ),
    ]
